/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPerfisRouteImport } from './routes/admin/perfis'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminVerificacoesRouteImport } from './routes/admin/verificacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerfisRoute = AdminPerfisRouteImport.update({
  id: '/admin/perfis',
  path: '/admin/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificacoesRoute = AdminVerificacoesRouteImport.update({
  id: '/admin/verificacoes',
  path: '/admin/verificacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/design-system': typeof DesignSystemRoute
  '/experiencias': typeof ExperienciasRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/seguranca': typeof SegurancaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/design-system': typeof DesignSystemRoute
  '/experiencias': typeof ExperienciasRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/seguranca': typeof SegurancaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/design-system': typeof DesignSystemRoute
  '/experiencias': typeof ExperienciasRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/seguranca': typeof SegurancaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conexoes'
    | '/design-system'
    | '/experiencias'
    | '/mensagens'
    | '/perfil'
    | '/premium'
    | '/seguranca'
    | '/admin/login'
    | '/admin/perfis'
    | '/admin/relatorios'
    | '/admin/verificacoes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conexoes'
    | '/design-system'
    | '/experiencias'
    | '/mensagens'
    | '/perfil'
    | '/premium'
    | '/seguranca'
    | '/admin/login'
    | '/admin/perfis'
    | '/admin/relatorios'
    | '/admin/verificacoes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/conexoes'
    | '/design-system'
    | '/experiencias'
    | '/mensagens'
    | '/perfil'
    | '/premium'
    | '/seguranca'
    | '/admin/login'
    | '/admin/perfis'
    | '/admin/relatorios'
    | '/admin/verificacoes'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConexoesRoute: typeof ConexoesRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ExperienciasRoute: typeof ExperienciasRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRoute
  PremiumRoute: typeof PremiumRoute
  SegurancaRoute: typeof SegurancaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPerfisRoute: typeof AdminPerfisRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminVerificacoesRoute: typeof AdminVerificacoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/perfis': {
      id: '/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AdminPerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verificacoes': {
      id: '/admin/verificacoes'
      path: '/admin/verificacoes'
      fullPath: '/admin/verificacoes'
      preLoaderRoute: typeof AdminVerificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConexoesRoute: ConexoesRoute,
  DesignSystemRoute: DesignSystemRoute,
  ExperienciasRoute: ExperienciasRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRoute,
  PremiumRoute: PremiumRoute,
  SegurancaRoute: SegurancaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPerfisRoute: AdminPerfisRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminVerificacoesRoute: AdminVerificacoesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
